java_binary(
    name = "main",
    srcs = glob(["*.java"]),
    main_class = "main.java.com.main.Main",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/lexer",
        "//src/main/java/com/repl",
        "//src/main/java/com/token",
    ],
)
