java_library(
    name = "parser",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/ast",
        "//src/main/java/com/lexer",
        "//src/main/java/com/token",
    ],
)
